name: Validate Python
on:
  push:
    branches:
    - main

jobs:
  setup-pypy-noenv:
    name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }} (noenv)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        pypy: ['pypy3.9']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: setup-python ${{ matrix.pypy }}
      id: setup-python
      uses: ./
      with:
        python-version: ${{ matrix.pypy }}
        update-environment: false
    
    - name: PyPy and Python version
      run: ${{ steps.setup-python.outputs.python-path }} --version
    
    - name: Run simple code
      run: ${{ steps.setup-python.outputs.python-path }} yara-update/yara-update.py