name: Validate Python
on:
  push:
    branches:
    - main

jobs:
  setup-pypy-noenv:
    name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }} (noenv)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        pypy: ['pypy3.9']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: setup-python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
        architecture: x64
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r yara-update/requirements.txt
    
    - name: PyPy and Python version
      run: python3 --version; pip3 --version
    
    - name: Run simple code
      run: python3 yara-update/yara-update.py